syntax on
set number
set cursorline
set cursorcolumn

call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-ragtag'
Plug '907th/vim-auto-save'
Plug 'benjifisher/matchit.zip'
Plug 'bogado/file-line'
Plug 'bhurlow/vim-parinfer'
Plug 'brookhong/DBGPavim'
Plug 'cakebaker/scss-syntax.vim'
Plug 'davidhalter/jedi-vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'elixir-lang/vim-elixir'
Plug 'ervandew/supertab'
Plug 'groenewege/vim-less'
Plug 'hynek/vim-python-pep8-indent'
Plug 'kien/ctrlp.vim'
Plug 'lepture/vim-jinja'
Plug 'mustache/vim-mode'
Plug 'neomake/neomake'
Plug 'rking/ag.vim'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-markdown'
Plug 'tpope/vim-pathogen'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'
Plug 'vim-scripts/TeX-PDF'
Plug 'scrooloose/nerdtree'
Plug 'ns9tks/vim-autocomplpop'
Plug 'sukima/xmledit'
call plug#end()
