vim.keymap.set("n",  "<leader>gs", vim.cmd.Git)
vim.keymap.set("n",  "<leader>ga", (':Git add .\n'))
vim.keymap.set("n",  "<leader>gc", (':Git commit -am "'))
vim.keymap.set("n",  "<leader>gp", (':Git push\n'))
vim.keymap.set("n",  "<leader>gP", (':Git pull\n'))
vim.keymap.set("n",  "<leader>gd", (':Git diff\n'))
vim.keymap.set("n",  "<leader>gf", (':Git fetch\n'))
